name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release Version (optional)"
        required: false

jobs:
  checkout:
    name: "Checkout Repository"
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.get-build-number.outputs.build_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # We need this to get (git rev-list --count HEAD) to work

      - name: Get build number
        id: get-build-number
        # The variables below can be referenced as ${{ needs.checkout.outputs.branch_name }} and ${{ needs.checkout.outputs.build_number }}
        run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          echo "Build number: $BUILD_NUMBER"
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_STATE

  build:
    name: "Build project and publish NPMs"
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"
          scope: "@syncmaven" # Replace with your npm scope if needed
          always-auth: true

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build PNPM project
        run: pnpm build && pnpm test

      - name: Test PNPM project
        run: pnpm test

      - name: Publish canary version to NPM
        if: github.ref == 'refs/heads/main' && github.event.inputs.release-version == ''
        run: pnpm release:canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish release version to NPM
        if: github.event.inputs.release-version != ''
        run: pnpm release --version ${{ github.event.inputs.release-version }} --publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-docker:
    runs-on: ubuntu-latest
    needs: [checkout, build]
    strategy:
      matrix:
        arch: [arm64, amd64]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ matrix.arch }}
          restore-keys: |
            ${{ runner.os }}-docker

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push release docker images
        if: github.event.inputs.release-version != ''
        run: docker buildx build --platform linux/${{ matrix.arch }} --tag syncmaven/syncmaven:v${{ github.event.inputs.release-version }} --tag syncmaven/syncmaven:latest --push .
      - name: Build and push canary docker images
        if: github.ref == 'refs/heads/main' && github.event.inputs.release-version == ''
        run: docker buildx build --platform linux/${{ matrix.arch }} --tag syncmaven/syncmaven:canary-v${{ needs.checkout.outputs.build_number }}  --tag syncmaven/syncmaven:canary --push .


#  manifest:
#    runs-on: ubuntu-latest
#    needs: build-docker
#    steps:
#      - name: Log in to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Create and push manifest list
#        run: |
#          if [ "${{ github.event.inputs.release-version }}" != "" ]; then
#            docker manifest create syncmaven/syncmaven:v${{ github.event.inputs.release-version }} --amend syncmaven/syncmaven:canary-amd64 --amend syncmaven/syncmaven:canary-arm64
#            docker manifest push syncmaven/syncmaven:v${{ github.event.inputs.release-version }}
#          else
#            docker manifest create syncmaven/syncmaven:canary --amend syncmaven/syncmaven:canary-amd64 --amend syncmaven/syncmaven:canary-arm64
#            docker manifest push syncmaven/syncmaven:canary
#          fi
