name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version (optional)'
        required: false

jobs:
  build-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build and test
        run: |
          pnpm build
          pnpm test

      - name: Publish to NPM
        run: |
          pnpm ${{ if github.event.inputs.release-version }}release --version ${{ github.event.inputs.release-version }} --publish${{ else }}release:canary${{ endif }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, amd64]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ matrix.arch }}
          restore-keys: |
            ${{ runner.os }}-docker

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            ${{ if github.event.inputs.release-version }} \
              --tag syncmaven/syncmaven:v${{ github.event.inputs.release-version }} \
              --tag syncmaven/syncmaven:latest \
            ${{ else }} \
              --tag syncmaven/syncmaven:canary-${{ matrix.arch }} \
            ${{ endif }} \
            --push \
            .

  manifest:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest list
        run: |
          docker manifest create syncmaven/syncmaven:${{ if github.event.inputs.release-version }}v${{ github.event.inputs.release-version }}${{ else }}canary${{ endif }} \
            --amend syncmaven/syncmaven:canary-amd64 \
            --amend syncmaven/syncmaven:canary-arm64
          docker manifest push syncmaven/syncmaven:${{ if github.event.inputs.release-version }}v${{ github.event.inputs.release-version }}${{ else }}canary${{ endif }}
