name: "Code checks and tests"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
env:
  # not entirely necessary, so far, but it's good to control where pnpm stores its cache
  # for future use
  # edit - PNPM is not reading this option
  PNPM_HOME: /pnpm
  HUSKY: 0
  TEST_POSTGRES: ${{ secrets.TEST_POSTGRES }}
  TEST_BIGQUERY: ${{ secrets.TEST_BIGQUERY }}
  TEST_SNOWFLAKE: ${{ secrets.TEST_SNOWFLAKE }}

jobs:
  build:
    name: "Build, check and test project"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Display versions of tools
        run: |
          echo "Node version: $(node --version), npm version: $(npm --version), pnpm version: $(pnpm --version)"

      - name: Get pnpm store
        id: pnpm-store
        run: |
          echo "Using PNPM store at $(pnpm store path)"
          echo "dir=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.dir }}
          key: "${{ runner.os }}-pnpm-${{ hashFiles('./pnpm-lock.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Check code style
        run: pnpm format:check:all

      - name: Build PNPM project
        run: pnpm build

      - name: Test PNPM project
        run: pnpm test
